version: "3.0"

services:

  app:
      build: .
      command: npm start
      ports:
        - "3000:3000"
      extra_hosts:
      - host.docker.internal:host-gateway
      environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8080
      restart: always


